### ISSUE TITLE
[Cookbook] Document how to dump a static 404 page

### ISSUE THREAD

**Issue by ogizanagi** [StenopePHP/Stenope#112]
For instance:

```yml
errors_404:
    path: 404.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: errors/404.html.twig
    options:
        stenope:
            sitemap: false
```

will dump a `404.html` file you can reference in Nginx config as the 404 page.
This is also the path used by Github pages on 404 errors.

https://github.com/Elao/elao_/blob/1024a09b17fe4b54c6e9be85377c0b1929447c95/config/routes.yaml#L21-L28
