### ISSUE TITLE
Configure/disable default processors

### ISSUE THREAD

**Issue by ogizanagi** [StenopePHP/Stenope#90]
As we don't want to impose anything, really, and since the list of processors we'll provide & decide to integrate or not by default with some arbitrary config will undoubtedly grow, it might be great to think about a better way to configure these and allow to disable some of them.
That'll also save some "hacks" where we override the service definition provided by the bundle by service id / FQCN.

Perhaps each of the default processors we'll provide should be exposed in the config with `canBeDisabled` and for the most relevant ones, expose some config keys.

Some processors might even be simpler to just be registered on need in userland.

No urge right now, be let's keep that in mind 😄

**Comment by ogizanagi** [comment]
Here's what such config could look like, given the existing processors bundled here (excluding the most basic / "non-intrusive" ones):

```yaml
stenope:
  processors:
    content_property: content # Key used by default processors to access and modify the main text of your contents
    
    assets: ~ # (canBeDisabled) AssetsProcessor: Attempt to resolve local assets URLs using the Asset component for images and links.
    
    last_modified: # (canBeDisabled) LastModifiedProcessor
      property: lastModified # Key used to inject the last modified date of the content according to its provider.
      git_path: git # Path to the git executable. False to disable fetching of the latest commit for a file.
      
    external_link_blank: # (canBeDisabled) HtmlExternalLinksProcessor: Add target="_blank" to external links
    
    anchors: ~  # (canBeDisabled) HtmlAnchorProcessor
    
    html_title: # (canBeDisabled) ExtractTitleFromHtmlContentProcessor: Extract a content title from a HTML property by using the first available h1 tag.
      title: # Key used to inject the title

    html_title_ids: ~ # (canBeDisabled) HtmlIdProcessor: Add ids to title in the content

    code_highlight: ~ # (canBeDisabled) CodeHighlightProcessor: syntax highlighting for code blocks

    toc: # (canBeDisabled) CodeHighlightProcessor: syntax highlighting for code blocks
      property: tableOfContent # Key used to configure and inject the TableOfContent object
      min_depth: 2
      max_depth: 6
```
